[phases.setup]
aptPkgs = [
    "ffmpeg", 
    "chromium", 
    "chromium-chromedriver",
    "xvfb"
]

[phases.build]
nixPkgs = [
    "chromium"
]

[start]
command = "python -m uvicorn web_ui:app --host 0.0.0.0 --port $PORT"
