[phases.setup]
aptPkgs = [
    "ffmpeg", 
    "chromium", 
    "chromium-driver",
    "xvfb"
]

[phases.build]
nixPkgs = [
    "chromium",
    "chromium-driver"
]

[start]
command = "python -m uvicorn web_ui:app --host 0.0.0.0 --port $PORT"
