[phases.setup]
aptPkgs = [
    "ffmpeg", 
    "chromium", 
    "chromium-chromedriver",  # Changed from chromium-driver
    "xvfb",
    "wget",
    "curl"
]

[phases.build]
nixPkgs = [
    "chromium", 
    "chromium-chromedriver"
]

[start]
command = "python -m uvicorn web_ui:app --host 0.0.0.0 --port $PORT"

